"""empty message

Revision ID: fb45295f875e
Revises: 1102d5c6def1
Create Date: 2020-03-25 23:40:20.886542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb45295f875e'
down_revision = '1102d5c6def1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('cars', sa.Column('color', sa.String(), nullable=True))
    op.drop_column('cars', 'name')
    op.drop_column('cars', 'model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cars', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('cars', 'color')
    op.drop_column('cars', 'brand')
    # ### end Alembic commands ###
